# Simple configuration for distributed preprocessing
# Each server automatically processes all available pflotran data
servers:
  - host: "165.132.33.30"  
    user: "geofluids"
    port: 22
    
  - host: "165.132.43.96"
    user: "geofluids" 
    port: 32125

  - host: "165.132.32.168"
    user: "geofluids" 
    port: 7777